### ISSUE TITLE
how do I solve this error ?, (fusilli-decorator-gtk:1282): Gtk-ERROR **: GTK+ 2.x symbols detected

### ISSUE THREAD

**Issue by JunioCalu** [noodlylight/fusilli#10]
I'm using mate gtk3 v1.9.1, and get this error when starting fusilli-decorator-gtk --replace;

(fusilli-decorator-gtk:1282): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap (imagem do núcleo gravada)

**Comment by noodlylight** [comment]
It looks like fusilli-decorator-gtk is incompatible with marco-1.9 (due to gtk3)

Go to fsm->decoration->fusilli-decorator-gtk and select Cairo as the Decoration Style.

If this doesn't work, you will have to recompile without marco support (passing --disable-marco to ./autogen.sh)

**Comment by JunioCalu** [comment]
Thank works now with "--disable-marco." I have some questions, how do I change the theme of the window? I'm also missing compiz Some plugins, such as automatic resize and Shift Switcher

**Comment by noodlylight** [comment]
Since you cannot use marco, metacity themes are not available.

You can either use the standard cairo theme, or use [rotini](https://github.com/noodlylight/rotini) (with emerald themes)

Eventually, I want to port all/most of the compiz plugins (time permitting). Which plugin is the automatic resize?

**Comment by JunioCalu** [comment]
the name is grid

**Comment by noodlylight** [comment]
Good, grid and staticswitcher go to the front of the TODO list.

**Comment by JunioCalu** [comment]
will stay cool, xd

**Comment by noodlylight** [comment]
Plugin grid is ready.

**Comment by noodlylight** [comment]
Plugin staticswitcher is also ready (but needs polishing)

**Comment by JunioCalu** [comment]
Wow, I'll test it now
