### ISSUE TITLE
black screen running in an xfce session

### ISSUE THREAD

**Issue by fossfreedom** [noodlylight/fusilli#11]
Hi,

  have now managed to make and install in Ubuntu 14.04 running a xfce4 session in a virtualbox vm (host is also ubuntu 14.04).  3D Acceleration is set as has 128Mb virtualised display RAM with virtualbox guest additions correctly installed.

When running LD_LIBRARY_PATH=/usr/local/lib fusilli --replace all I get is a black screen

It appears that the virtualmachine just hangs - I cant get another TTY to look at dmesg or Xorg.log.

Any thoughts on how I can debug this further?

**Comment by noodlylight** [comment]
Hi again,

You can try fusilli --debug --replace &> ~/logfile.txt and check logfile.txt after rebooting.

**Comment by fossfreedom** [comment]
thanks.

<pre>
libGL error: pci id for fd 7: 80ee:beef, driver (null)
OpenGL Warning: glFlushVertexArrayRangeNV not found in mesa table
OpenGL Warning: glVertexArrayRangeNV not found in mesa table
OpenGL Warning: glCombinerInputNV not found in mesa table
OpenGL Warning: glCombinerOutputNV not found in mesa table
OpenGL Warning: glCombinerParameterfNV not found in mesa table
OpenGL Warning: glCombinerParameterfvNV not found in mesa table
OpenGL Warning: glCombinerParameteriNV not found in mesa table
OpenGL Warning: glCombinerParameterivNV not found in mesa table
OpenGL Warning: glFinalCombinerInputNV not found in mesa table
OpenGL Warning: glGetCombinerInputParameterfvNV not found in mesa table
OpenGL Warning: glGetCombinerInputParameterivNV not found in mesa table
OpenGL Warning: glGetCombinerOutputParameterfvNV not found in mesa table
OpenGL Warning: glGetCombinerOutputParameterivNV not found in mesa table
OpenGL Warning: glGetFinalCombinerInputParameterfvNV not found in mesa table
OpenGL Warning: glGetFinalCombinerInputParameterivNV not found in mesa table
OpenGL Warning: glDeleteFencesNV not found in mesa table
OpenGL Warning: glFinishFenceNV not found in mesa table
OpenGL Warning: glGenFencesNV not found in mesa table
OpenGL Warning: glGetFenceivNV not found in mesa table
OpenGL Warning: glIsFenceNV not found in mesa table
OpenGL Warning: glSetFenceNV not found in mesa table
OpenGL Warning: glTestFenceNV not found in mesa table
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
</pre>

I had a check with the standard compiz that comes with ubuntu (v0.9) i.e. compiz --replace

That works fine.

Thus - any thoughts on what extra do I need to compile with fusilli to force loading of the virtualbox graphics drivers?

**Comment by noodlylight** [comment]
Compiz 0.9 can load even without opengl. (obviously most features would be unavailable)

Can you check glxgears/glxinfo?

**Comment by fossfreedom** [comment]
yep glxgears under compiz shows the spinning gears as well as a similar trace - so the virtualbox graphics drivers error message is a red-herring?

<pre>
libGL error: pci id for fd 4: 80ee:beef, driver (null)
OpenGL Warning: glFlushVertexArrayRangeNV not found in mesa table
OpenGL Warning: glVertexArrayRangeNV not found in mesa table
OpenGL Warning: glCombinerInputNV not found in mesa table
OpenGL Warning: glCombinerOutputNV not found in mesa table
OpenGL Warning: glCombinerParameterfNV not found in mesa table
OpenGL Warning: glCombinerParameterfvNV not found in mesa table
OpenGL Warning: glCombinerParameteriNV not found in mesa table
OpenGL Warning: glCombinerParameterivNV not found in mesa table
OpenGL Warning: glFinalCombinerInputNV not found in mesa table
OpenGL Warning: glGetCombinerInputParameterfvNV not found in mesa table
OpenGL Warning: glGetCombinerInputParameterivNV not found in mesa table
OpenGL Warning: glGetCombinerOutputParameterfvNV not found in mesa table
OpenGL Warning: glGetCombinerOutputParameterivNV not found in mesa table
OpenGL Warning: glGetFinalCombinerInputParameterfvNV not found in mesa table
OpenGL Warning: glGetFinalCombinerInputParameterivNV not found in mesa table
OpenGL Warning: glDeleteFencesNV not found in mesa table
OpenGL Warning: glFinishFenceNV not found in mesa table
OpenGL Warning: glGenFencesNV not found in mesa table
OpenGL Warning: glGetFenceivNV not found in mesa table
OpenGL Warning: glIsFenceNV not found in mesa table
OpenGL Warning: glSetFenceNV not found in mesa table
OpenGL Warning: glTestFenceNV not found in mesa table
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
303 frames in 5.0 seconds = 60.589 FPS
302 frames in 5.0 seconds = 60.214 FPS
300 frames in 5.0 seconds = 59.817 FPS
301 frames in 5.0 seconds = 60.005 FPS
</pre>

glxinfo: http://paste.ubuntu.com/9660879/

**Comment by fossfreedom** [comment]
ok  - after further investigations

with mesa-utils installed:
cd /usr/local/lib
fusilli --replace

This seems to work ok. Wobbly windows works great :)

without mesa-utils installed:
cd /usr/local/lib
fusilli --replace &

The screen rotates 180degrees! And the virtual machine appears to hang.

Thus the key package messing was mesa-utils.  Thanks again.
