### ISSUE TITLE
Plugins Resize and Move: no way to Uninitiate with the keyboard

### ISSUE THREAD

**Issue by hhhorb** [noodlylight/fusilli#12]
Hey noodly! Awesome work on this, as I said before. I see many issues (mostly ones that were already in Compiz 0.8 as I remember it), but this is a usability one that I don't remember...

Steps to reproduce...
1. Enable the Move and Resize plugins.
2. Use a keyboard shortcut to move or resize your window.
3. Try and leave your window moved or resized without the mouse... ?

As I remember it, in Compiz you could hit Enter to finish your move/resize, in Fusilli that does nothing. I think you could also hit Esc, in Fusilli that resets the window to it's original size/location (may have been that way in Compiz too). I've also tried repeating tthe keyboard shortcut, which is what the old wiki suggests, but that also does nothing...

http://wiki.compiz.org/Plugins/Move

Off topic, what's the best way to install updates, make uninstall the old version first? Thanks again for your time!

**Comment by noodlylight** [comment]
Hello,

Good catch, fixed.

> Off topic, what's the best way to install updates, make uninstall the old version first? Thanks again for your time!

Another solution is to install in a disposable directory (e.g. ~/testing), test the new version (with ~/testing/bin/fusilli --replace) and when you are over, you simply delete the the temporary directory (~/testing).

**Comment by hhhorb** [comment]
Hey M,

Fixed already? You're not messing around! Cheers,

H
