### ISSUE TITLE
no interaction with nvidia drivers?

### ISSUE THREAD

**Issue by beku** [noodlylight/fusilli#16]
& fusilli --replace
Fusilli Window Manager
Version: 0.0.0
Built with inotify support
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
fusilli (core) - Info: Loading plugin: move
fusilli (core) - Info: Loading plugin: resize
fusilli (core) - Info: Loading plugin: decoration
/bin/sh: fusilli-decorator-gtk: Kommando nicht gefunden.
^Cfusilli (core) - Info: Unloading plugin: decoration
fusilli (core) - Info: Unloading plugin: resize
fusilli (core) - Info: Unloading plugin: move

I tried fusilli on a system running successfully openSUSE's compiz.-0.8 . The nvidia propriarity driver is loaded. After loading fusilli the desktop view is frozen :-/ However, Ctrl-C frees the desktop and I could start an other WM again :-)

**Comment by noodlylight** [comment]
Issue fixed by DOGE.
![](http://ask-doge.com/doge.png)
