### ISSUE TITLE
Multiple desktops and multiple viewports - Native way to navigate multiple desktops AND viewports?

### ISSUE THREAD

**Issue by ShadowKyogre** [noodlylight/fusilli#2]
I noticed you left the multiple desktop configuration in the core plugin. I wanted to let you know about a [wnck bug](https://bugzilla.gnome.org/show_bug.cgi?id=725290) that doesn't properly detect multiple workspaces since the check for the number of desktop atoms pairs is faulty. This can lead to people not knowing where some windows went if they accidentally send them to desktop X when they mean viewport X on their current desktop.

Currently one can work around this issue with an app that's capable of this on its own, like [Compiz Boxmenu (link also contains the details on why I added desktop menu to complement viewport menus)](https://github.com/ShadowKyogre/Compiz-Boxmenu/issues/2).

I'd like it if libwnck fixed this upstream, but I still haven't heard from them.

On a related note, would it be possible to port the [vpswitch](http://cgit.compiz.org/compiz/plugins/vpswitch/tree/?h=compiz-0.8) plugin so one can launch an application by clicking on the desktop?
Same with the [workspacenames](http://cgit.compiz.org/~maniac/workspacenames/tree/) (<- this is a 0.9.x plugin, but I think the code looks simple enough to backport) so users can easily see which desktop/viewport combo they're on?

[EDIT]: I'm not sure if I can compile the current compiz plugins against fusilli, as I don't see any detailed steps on how to do that. Does it just pick these up automagically?

**Comment by noodlylight** [comment]
Oops, I forgot about this. I'll add the dbus signal ASAP. ShadowKyogre, sorry for the ridiculous delay.
