### ISSUE TITLE
wall plugin shouldn't react on mouse scrolling

### ISSUE THREAD

**Issue by NiceandGently** [noodlylight/fusilli#20]
For some reasons mouse srolling switch the viewport, which ends up in an unfinished action if next viewport has a maximize window.
Here mouse srolling from wall plugin stoped working because of the maximize window.
In result the viewport is unusable and you see only the previews of the wall plugin.
Switching back with a keyboard command to another viewport helps at that point.
I'm still wondering why switching a viewport is possible with mouse scrolling, i didn't find any setting for that in fsm, but maybe i miss something.
Also i never saw this behaviour with compiz.

**Comment by NiceandGently** [comment]
Ok, i found the culprit.
After i removed the key commands '<ClickOnDesktop>Button4' and '<ClickOnDesktop>Button5' in wall plugin settings, the issue is gone.
Couriously i use a 3 button mouse, not a 5 button mouse.
I think both keys shouldn't enabled as default, imo, because a fusilli beginner can be going crazy about :)
But it's up to you to decide if it's a issue or not.

**Comment by noodlylight** [comment]
Yes, tag <ClickOnDesktop> is new. (not possible in compiz)

In Compiz, changing workspaces with the wheel was accomplished using a plugin (vpswitch).

**Comment by noodlylight** [comment]
> I think both keys shouldn't enabled as default, imo, because a fusilli beginner can be going crazy about :)
> But it's up to you to decide if it's an issue or not.

It is probably a good idea.

I want to first add support for large texts in fsm (to note how to enable this behavior) and then I'll remove the related default bindings in rotate and wall.

**Comment by NiceandGently** [comment]
> I want to first add support for large texts in fsm (to note how to enable this behavior) and then I'll remove the related default bindings in rotate and wall.
nice, addining more infos for users sounds like a good idea .
> In Compiz, changing workspaces with the wheel was accomplished using a plugin (vpswitch).

> Related commit: 3163a20
I'm only wondering why button 4/5 is the srollwheel with a 3 button mouse.

**Comment by noodlylight** [comment]
> I'm only wondering why button 4/5 is the srollwheel with a 3 button mouse.

It's X11 terminology. :)

More: http://stackoverflow.com/questions/15510472/scrollwheel-event-in-x11
