### ISSUE TITLE
Can't build on Ubuntu MATE 14.04

### ISSUE THREAD

**Issue by cvetan** [noodlylight/fusilli#22]
I am trying to install this on Ubuntu MATE 14.04 since i am having trouble with compiz, and i have tearing also.

But i am getting bunch of errors, when i try to ./autogen.sh

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal 
configure.ac:40: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:40: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
autoreconf: Leaving directory `.'
./autogen.sh: 10: ./autogen.sh: glib-gettextize: not found

Is there a way to fix this?

**Comment by noodlylight** [comment]
I think that "sudo apt-get install libglib2.0-dev" should work.

**Comment by cvetan** [comment]
It solved some of the issues, but some still persist. :(

http://paste.ubuntu.com/11330765/

And when i try to run make, after autogen.sh it says no arguments.

**Comment by noodlylight** [comment]
You could try installing the following packages: xorg-dev, x11proto-composite-dev, x11proto-xext-dev, libxcb-xfixes0-dev, libxdamage-dev, libxrandr-dev, libxinerama-dev, libxslt1-dev, libpangocairo-1.0-0, dbus

Also, "sudo apt-get build-dep compiz" will install all required packages to compile compiz, which should cover the needs for fusilli.

**Comment by noodlylight** [comment]
> And when i try to run make, after autogen.sh it says no arguments.

I think this is normal, since autogen.sh failed.

**Comment by cvetan** [comment]
It installed, aldo i think not good it doesn't load plugins, doesn't work well. How can i run it? Is there some guide somewhere?

**Comment by noodlylight** [comment]
You can run it with ./fusilli --replace from a terminal.

No guide at the moment.

**Comment by cvetan** [comment]
It works, but didn't load gtk decorations.

**Comment by noodlylight** [comment]
Do ./fusilli-decorator-gtk --replace in another terminal.

**Comment by cvetan** [comment]
I did it, restarted computer, but it wont display gtk decorations. All plugins work, animations all... except decorations. :(

**Comment by noodlylight** [comment]
You could check if plugin decoration is enabled in fsm.

**Comment by cvetan** [comment]
It is.

**Comment by noodlylight** [comment]
Can you get a screenshot? Are there any error messages?

**Comment by cvetan** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/5733322/7789003/002c7b18-0252-11e5-9a23-6efa71180a75.png)

**Comment by cvetan** [comment]
Ni there are no errors.

**Comment by noodlylight** [comment]
As I understand you want metacity theme decorations, not the cairo theme.

I think the issue is that fusilli was compiled without marco support. 

You could try installing packages libmarco-dev, libmarco-private0 and recompile fusilli.

When autogen.sh finishes sucessfully, there is a line that indicates if marco themes would be available.

**Comment by cvetan** [comment]
I tried it, and got this output:

the following optional plugins will be compiled:
  svg:      yes

and the following optional features will be compiled:
  inotify:                 yes
  fusilli-decorator-gtk:   no
       marco themes:       no
  fusilli-decorator-kde4:  no
  fsm:                     yes

Is there a way to specify what will be compiled?

**Comment by noodlylight** [comment]
By default, the script will try to install everything, provided that the dependencies are fulfilled.

You can disable individual options using --disable-inotify, --disable-librsvg (disables the svg plugin), --disable-gtk (disables fusilli-decorator-gtk), --disable-marco, --disable-kde4, --disable-fsm     

> fusilli-decorator-gtk: no

To fix this, you should try installing libxrender-dev, libgtk2.0-dev, libxml2-dev, libwnck-dev, libpangocairo-1.0-0

> marco themes: no

For this libmarco-dev
