### ISSUE TITLE
Possible to add auto-tab and auto-group to the group plugin?

### ISSUE THREAD

**Issue by ShadowKyogre** [noodlylight/fusilli#23]
The 0.9 series has options to configure match groups for tabs and groups: http://bazaar.launchpad.net/~compiz-team/compiz/0.9.12/view/head:/plugins/group/group.xml.in

It would be nice if there was a way to backport it to fusilli and to make it less buggy than the implementation in 0.9 (which crashes the last time I tried it).

**Comment by noodlylight** [comment]
I just added autotabbed window matches. (fsm->Tabbing->Misc. Options)

Should I add autogrouping too? Could you point me to the related options in 0.9?

**Comment by ShadowKyogre** [comment]
There isn't auto-grouping (as in grouping on window creating) in 0.9, even though there's auto-tabbing. I'd think that implementing it would be similar to auto-tabbing windows on creation.

**Comment by noodlylight** [comment]
I looked at this and I think that auto grouping is not very useful: when a new window is opened, it usually appears on a specific position. So, with auto-grouping you would get multiple windows placed and grouped/locked on the exact some spot.

**Comment by ShadowKyogre** [comment]
@noodlylight: Huh, that is true. That's especially so for gvim (which I just ran in the virtual machine for testing to make sure there were cases I wasn't aware of). 

The initial case I thought autogrouping could be useful for is those applications which have multiple windows showing a separate part of the UI (like Skype and multi-window gimp, even though I have gimp in single-window mode).

I suppose we can close this then now that auto-tabbing is implemented?

**Comment by noodlylight** [comment]
> I suppose we can close this then now that auto-tabbing is implemented?

Probably :)
