### ISSUE TITLE
mate-panel disappears when starting fusilli

### ISSUE THREAD

**Issue by noodlylight** [noodlylight/fusilli#4]
Upon starting fusilli, mate-panel disappears. 

Sometimes just the taskbar, sometimes just the upper bar (Applications,Places,System), sometimes both.

If clicked on, it may reappear again (sometimes it takes a lot of effort)

The bug also exists in compiz-0.8.9

**Comment by NiceandGently** [comment]
@noodlylight
i found out that enable 'force syncronisation between X and GLX' from workarounds fix the issue with compiz-0.88, same for fusilli if i switch from compiz to fusilli.

**Comment by noodlylight** [comment]
@NiceandGently 
Good! Sounds like a start...
![](http://i3.kym-cdn.com/photos/images/newsfeed/000/114/139/tumblr_lgedv2Vtt21qf4x93o1_40020110725-22047-38imqt.jpg)

**Comment by noodlylight** [comment]
I haven't noticed this bug for a while, even with plugin workarounds disabled.

I think that the pull request by NiceandGently that added glXWaitX fixed it. 

Commit for future reference: 114fcc06dd96db4354ebd4d801a64816bed3e9d1
