### ISSUE TITLE
trying to compile the fusilli decorator

### ISSUE THREAD

**Issue by fossfreedom** [noodlylight/fusilli#9]
Hi,
  I'm using ubuntu 14.04 running the xfce desktop

I've managed to work out most of the dev libraries to install. After running ./autogen.h the last part of the output is:

and the following optional features will be compiled:
  inotify:                 yes
  fusilli-decorator-gtk:   no
       marco themes:       no
  fusilli-decorator-kde4:  no
  fsm:                     yes

How do I compile in the fusilli-decorator-gtk ? 

Looking back I can see "checking for GTK_WINDOW_DECORATOR... no" - any thoughts on what the possible package name is for this?

**Comment by noodlylight** [comment]
Hi!

fusilli-decorator-gtk depends on xrender, gtk2, libwnck, libxml and pangocairo.

libxml and pangocairo are also requirements for fusilli(which you have covered), so you should look at xrender, gtk2, libwnck.

**Comment by fossfreedom** [comment]
thanks!

the missing library was libwnck-dev

cheers
